### ISSUE TITLE
MVP List/Schema

### ISSUE THREAD

**Issue by mmcnulty20** [arieltlr/PinandNeedle#1]
## MVP List

- [x] Fix bullet point indentation for ease of reading (minor)
- [x] Demo user should be given full functionality of the app (so recruiters aren’t required to create an account)
- [x] Readme will be done last!
- [x] Boards and Pins should be separate MVPs (with boards first)
- [x] Typo: ‘board shoes preview’
- [x] Can users delete or edit existing pins? Saved pins? Boards? Be especially explicit where CRUD functionality is occurring.
- [x] “More like this” when clicking a pin will likely be difficult to implement - let me know if you currently have a plan for a simplified version, otherwise it should be a bonus feature
- [x] Message me to discuss MVP ordering - we'll likely integrate profile with boards and pins 
- [x] Discover needs more detail in what is covered by MVP - as it is, it seems like it serves a presentational purpose for some static info (which is totally fine, but could be part of the pins MVP), and a search bar
- [x] Follows might want to be a bonus functionality

## Schema

- [x] Minor formatting: put pieces that correspond to real code (like table and column names) in backticks 
- [x] Remove settings table and put `location`, `country`, and `language` on the users table, or message me with the purpose of the separate table
- [x] Remove `board_id` from settings (if settings remains) or message me with the purpose
- [x] Pins need to store their description
- [x] I believe an individual pin belongs to the user who uploads it (anyone can save it to a board)
- [x] With above, `users_pins` unnecessary
- [x] Let’s discuss boards (might want more information stored)
- [x] Note where tables should have unique combinations of two columns.
## Overall

Great job so far! Lots of detail, we’ll just need to discuss a few things to iron out specifics! :)

**Comment by arieltlr** [comment]
Hi Megan, thank you so much for your edits! I have a couple of questions: 
1. On the `users` table - for `country` and `language`, I want to store default values. I've thought through two solutions: 
    - Default store USA and English and the user can edit later if they want to
    - Leave them blank and let the user add them at a later point
    - Try to pull the users location from ownProps (is this possible?)
    - I am leaning towards the first option 
2. I added a note where a table had a unique combination of ids. Is that what you meant for you last piece of edit feedback? 
3. I changed my "More Like This" to be a bonus feature, in which pins with the same category tag are shown below a selected pin. My thought on adding a category pin to the database is that I need create a `tag` table and then create a joins table for `pin_id` and `tag_id`. I don't want to store an array of tags for the pin because iterating through an array is costlier than doing a table lookup. Should I add a table, `tags` and a joins table, `pins_tags` to my schema? Or only if I get to that bonus item?
4. Lastly, for MVP ordering, do you want to talk during class hours this week, or should I message you on slack?

**Comment by mmcnulty20** [comment]
Minor Schema things left around uniqueness in scope:
- [x] 	No need to say that it is a unique combination of columns with the unique identifier for that entry ( like `id` and `user_id` is a unique combination, or `user_id` and `session_token`), as there will never be a situation that would fail.
- [x] Can users have multiple boards with the same name? If not, that would be somewhere for a unique combination (`user_id` and `board_name`). 

Great work here! :)

**Comment by arieltlr** [comment]
Users cannot have a boards with the same name. I updated the name column with note that it is unique in scope to the user_id. Thanks for the catch!
