### ISSUE TITLE
Sample State & Frontend/Backend Routes

### ISSUE THREAD

**Issue by mmcnulty20** [arieltlr/PinandNeedle#2]
## Sample State
- [x] You will want to track a user’s pins and boards in the users slice of state through an array of ids (e.g. `createdBoards: [15, 16]`) - you *could* find this information in the mapStateToProps with selectors, but this will be much simpler to use
- [x] Follows do not need their own slice of state, but can be handled like above with followed users and followers. Likewise for `userPins` and `boardPins`
- [x] Schema review mentioned settings table, but even should that remain would there be a situations where we would need settings for users other than the current user? Are settings entities, or part of the UI?
- [x] Items should hold reference to things to which they belong (like pins should have a user id and board id)
- [x] Typo: sessions slice should store current users’s id, not `createUserId` (mechanically would be fine, but semantically unclear)
## Backend Routes
- [x] Not a requirement, but if for each route you mention a bit more specifics of the information you will send up with a request, *especially* other information (like if a route sends info about both users and pins) it will help a lot as you build this out later. For example, 
- [x] As to the note at the bottom: do boards not belong to a particular user?
- [x] `GET /api/users/:id` may be utilized for the profile, but for clarity we won’t want to make a separate request for user info directly associated with a pin - that should come with the request for that pin
- [x] You shouldn’t need to nest `GET /api/users/:id/boards/:id` - if we have the board id, that is already the specific unique reference for that board.
- [x] When would we make a `GET /api/follows` request that would be independent of the other requests here (like a user show)?
## Frontend Routes
- [x] Nav component contains searchbar (everywhere except splash)
- [x] It doesn’t seem as though the pinform renders on every page?
- [x] I don’t see a footer
- [x] login/sign up forms are modals and do not have their own routes
- [x] Looks as though BoardList will be inside the ShowPin component
- [x] Editing a pin happens via modal and not its own route
- [x] Have `/user/:id/edit/profile` twice
- [x] Similar to backend route questions, `/user/:id/boards/:id`: is there a reason behind this being nested? If you keep it, the wildcards will need distinct names.

**Comment by arieltlr** [comment]
Hi Megan - 

Going through the backend routes, I made the changes you suggested. 

1. I agree that board/:id does not need to be nested under the user because the board have their own table attached to userId. The board show page is sufficient. 
2. I removed the nested route `users/:id/boards`. Now that boards are stored in an array in the user slice of state, I don't think I need that nested route. I can use `userId` to make an `$a.jax` call to the backend for all the boards belonging to the specified `userId`.
3. Since follows is now part of the users slice of state I got rid of the `GET /api/follows` backend route.  

Frontend routes: 
1. The pinform does render on every page as a small, floating icon that you can click into. 
2. The foot renders as a small icon on the side of the page that you can click into in the same way as the pinform.
3. Correct that BoardList will be inside the ShowPin component. Is that ok as written?

**Comment by mmcnulty20** [comment]
As a note on backend route nesting/removing some backend routes - it is not at all about having their own location in state, and rather about our backend routes reflect *when* we’ll make a request. If information would all be returned at the same time (like when loading a certain page), it doesn’t need its own request. If it could be more efficiently loaded at a different time, or might be needed somewhere it isn’t yet, if will need its own route.
